### ISSUE TITLE
Progress on your project red black tree

### ISSUE THREAD

**Issue by yungyuc** [jonathan-liu-0204/Visualization-of-Red-Black-Tree#1]
I have not seen any activities in your project repository.  Do you need any help?

**Comment by jonathan-liu-0204** [comment]
Hi professor, 

Sorry, but actually I’ve withdrawn this course about a month ago. Hence, I haven’t made any changes since then. 
Thank you, professor.

Best regards, 
Jonathan Liu

**Comment by yungyuc** [comment]
Thank you very much for letting me know.  My apology for the out-dated record.

**Comment by jonathan-liu-0204** [comment]
Thank you, Professor.

Best Regards, 
Jonathan Liu
